Tenderly/hardhat-tenderly

README.md
Hardhat doesn't use `usePlugin` anymore. Instead, the module needs to be required or imported.
=> Replace usePlugin with require/import

package.json, yarn.lock
Hi,
Here's a quick PR to update axios to v0.21.1 and fix the [vulnerability](https://www.npmjs.com/advisories/1594) reported by `yarn audit`.
Cheers!
=> Update axios to v0.21.1

src/Tenderly.ts
I was trying to verify to Kovan in the absence of a --network:
```
await tenderly.verify({
name: "YourContract",
address: "0xa983e6e57b95c2e47cEE88B6a6bd67452fA9D24D",//yourContract.address,
network: "kovan"
})```
I got the following error:
`Error in hardhat-tenderly: Please provide a network via the hardhat --network argument or directly in the contract`
This change falls back to use `contract.network` if `this.env.hardhatArguments.network` is undefined
=> Contract network patch

src/index.ts
=> fix: use network metadata slug only when it exists

package.json, src/TenderlyNetwork.ts, src/tenderly/types/utils.ts
Addressing raised breaking change introduced in `v1.1.0` in #47
=> Removing `forkNetwork` as mandatory field in TenderlyConfig

packages/tenderly-hardhat/src/index.ts, packages/tenderly-hardhat/src/tenderly/extender.ts
This is needed to be done like this because if hardhat/ethers override ethers and if it is imported below @tenderly/hardhat-tenderly it will override our automatic verification implementation on ethers.
=> Fix ethers override

.changeset/angry-phones-train.md, packages/tenderly-hardhat/src/tenderly/types/utils.ts
We cannot import from `src` since it is our build directory. It won't be shown to the users.
=> Fix wrong import

.changeset/calm-oranges-perform.md, packages/tenderly-hardhat/package.json
Explanation can be found in [Move hardhat from dep to devDep #133](https://github.com/Tenderly/hardhat-tenderly/pull/133/files).
=> Move hardhat to dev dep

.changeset/six-toes-watch.md, packages/tenderly-hardhat/src/utils/util.ts
This PR resolves an issue where the user specifies `chainId` inside the `tenderly` network in `hardhat.config.ts`.
=> `chainId` inside specified `tenderly` network

.changeset/proud-cars-wait.md, packages/tenderly-hardhat/src/utils/util.ts
Enable clients to specify their own `chainId` in the `Network` configuration, thus have a special name for a network that they can link to a specific `chainId`.
=> Enable clients to specify their id inside Network configuration

.changeset/violet-keys-dream.md, packages/tenderly-hardhat/src/utils/util.ts
Firstly look if the client specified `chainId` in the network configuration, if not, then look in the base of tenderly's networks.
=> fix: enable clients to specify their id inside Network configuration

.changeset/slimy-cycles-clap.md, examples/contract-verification/package.json, examples/contract-verification/scripts/calculator/maths-deployment-ethers.ts, examples/contract-verification/scripts/greeter/automatic.ts, examples/contract-verification/scripts/greeter/manual-advanced-fork.ts, examples/contract-verification/scripts/greeter/manual-advanced.ts, examples/contract-verification/scripts/greeter/manual-simple.ts, examples/contract-verification/yarn.lock, package.json, packages/tenderly-core/package.json, packages/tenderly-core/src/internal/core/types/Contract.ts, packages/tenderly-hardhat/README.md, packages/tenderly-hardhat/package.json, packages/tenderly-hardhat/src/index.ts, packages/tenderly-hardhat/src/tenderly/ethers.ts, packages/tenderly-hardhat/src/tenderly/ethers/Contract.ts, packages/tenderly-hardhat/src/tenderly/ethers/ContractFactory.ts, packages/tenderly-hardhat/src/tenderly/extender.ts, packages/tenderly-hardhat/src/tenderly/types/Contract.ts, packages/tenderly-hardhat/src/type-extensions.ts, packages/tenderly-hardhat/src/utils/util.ts, yarn.lock
This PR migrates `@tenderly/hardhat-tenderly` to the new version of ethers-v6 along with the new version of `@nomicfoundation/hardhat-ethers`.
=> Migrate to ethers-v6

examples/contract-verification/README.md
I forgot to update the documentation in `examples/contract-verification` in the last PR.
=> Update examples/contract-verification documentation

.changeset/silly-shirts-do.md, packages/tenderly-hardhat/src/Tenderly.ts
We haven't returned the accumulator from `contracts.reduce` function resulting in an `undefined` new array.
This PR fixes that error.
=> Return accumulator from reduce function fix

packages/tenderly-hardhat/README.md, packages/tenderly-hardhat/src/tenderly/extender.ts
Add `TENDERLY_` prefix to `AUTOMATIC_POPULATE_HARDHAT_VERIFY_CONFIG` env variable to scope the env variable to the Tenderly domain.
=> Add TENDERLY_ prefix to env variable.

packages/tenderly-hardhat/src/errors.ts, packages/tenderly-hardhat/src/utils/util.ts
Improved chain ID resolution and error handling in the Tenderly Hardhat plugin.
- Created a new `UndefinedChainIdError` class for better error messaging
- Extracted chain ID resolution logic into a separate `getChainId` function
- Improved error handling when chain ID cannot be determined
- Standardized the chain ID resolution process across the plugin
1. Try verifying contracts on a network without a defined chain ID
2. Verify the new error message appears with the network name
3. Test contract verification on networks with valid chain IDs
4. Verify chain ID resolution works for both custom and predefined networks
To provide clearer error messages and better handle cases where chain IDs are undefined. This improves the developer experience by making it immediately clear when and why …
=> Improve chainId resolution and error handling

packages/tenderly-core/src/internal/core/common/errors.ts, packages/tenderly-core/src/internal/core/services/TenderlyService.ts, packages/tenderly-core/src/internal/core/types/VerifyContractABIRequest.ts, packages/tenderly-core/src/internal/core/types/VerifyContractABIResponse.ts, packages/tenderly-core/src/internal/core/types/index.ts, packages/tenderly-core/src/internal/lib/tenderly-lib.ts
Added support for verifying contract ABIs through the Tenderly API service.
- Introduced new `verifyContractABI` method in TenderlyService
- Added new error classes: `UnauthorizedError`, `InvalidResponseError`, and `BytecodeMissingMethodSignaturesError`
- Created new types `VerifyContractABIRequest` and `VerifyContractABIResponse`
- Exported new verification types through the tenderly-lib interface
1. Ensure you have a valid Tenderly access token
2. Create a `VerifyContractABIRequest` with:
- networkId
- contract address
- contract name
- ABI string
3. Call `verifyContractABI` with your username, project, and request object
4. Verify the response matches the expected `VerifyContractABIResponse` format
To provide developers with the ability to verify contract ABIs directly through the …
=> Implement client API request for verifyContractABI

packages/tenderly-core/src/internal/core/types/index.ts, packages/tenderly-core/src/internal/core/types/verification-types.ts, packages/tenderly-core/src/internal/lib/tenderly-lib.ts, packages/tenderly-hardhat/src/constants.ts, packages/tenderly-hardhat/src/utils/get-verification-type.ts
Moved verification types from hardhat package to core package and updated imports accordingly.
- Created new `verification-types.ts` file in tenderly-core package
- Moved `VERIFICATION_TYPES` constant from hardhat package to core package
- Updated imports to use the new location of `VERIFICATION_TYPES`
- Added export for verification types in core package index
1. Import `VERIFICATION_TYPES` from `@tenderly/api-client`
2. Verify the constant contains the expected values: "fork", "private", "public", and "devnet"
3. Ensure existing functionality using verification types continues to work as expected
Centralizes verification types in the core package, making them more accessible across different packages and reducing code duplication. This change follows better architectural practices by …
=> move VERIFICATION_TYPES to core

packages/tenderly-core/src/internal/core/services/TenderlyService.ts
Added support for contract ABI verification on both project and virtual network environments.
- Split contract ABI verification into two distinct paths: project verification and virtual network verification
- Added a new `verificationType` parameter to determine the verification path
- Created separate methods `verifyContractABIOnProject` and `verifyContractABIOnVnet` with appropriate API endpoints
- Enhanced error handling with specific context for each verification type
1. Verify a contract ABI on a project:
```typescript
await tenderlyService.verifyContractABI(username, project, VERIFICATION_TYPES.PUBLIC, request)
```
2. Verify a contract ABI on a virtual network:
```typescript
await tenderlyService.verifyContractABI(username, project, VERIFICATION_TYPES.PRIVATE, request)
```
3. Ensure …
=> Implement ABI verification depending on verificationType on tenderly-core

packages/tenderly-hardhat/src/Tenderly.ts, packages/tenderly-hardhat/src/verification/errors.ts, packages/tenderly-hardhat/src/verification/service.ts
Enhanced contract verification functionality in the Tenderly Hardhat plugin by adding support for different verification types and improving error handling.
- Added verification type checks before contract ABI verification
- Introduced automatic contract addition to projects before ABI verification
- Created new error handling for devnet verification attempts
- Restructured verification service to handle different network types (including virtual networks)
- Added support for fork ID usage in virtual network verifications
1. Attempt to verify a contract ABI on a regular network
2. Try verifying a contract on a virtual network to ensure fork ID is properly used
3. Verify that attempting to verify on devnet throws the appropriate error
4. Test automatic contract addition to project before …
=> Implement ABI verification depending on verificationType on tenderly-hardhat
